//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fight
    {
        public int WhiteParticipantId { get; set; }
        public int RedParticipantId { get; set; }
        public Nullable<decimal> WhitePoints { get; set; }
        public Nullable<decimal> RedPoints { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
    }
}
