//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudoApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JudoDBEntities : DbContext
    {
        public JudoDBEntities()
            : base("name=JudoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fight> Fights { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Sportsclub> Sportsclubs { get; set; }
        public virtual DbSet<Tatamy> Tatamies { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
